"""Support code for CSCI 4052U Lab 2.

Students do not edit this file.  It provides:

* data           -- ``MNISTDataModule`` (a fixed subsample of MNIST)
* models         -- ``LitClassifier`` (``training_step`` left for the student),
                    ``reference_conv_block`` used to check Exercise 1
* training       -- ``make_trainer``, ``History``
* plotting       -- ``show_digits``, ``plot_curves``, ``summary_table``
* verification   -- the ``check_*`` functions called after each student cell
"""

from __future__ import annotations

import math
from pathlib import Path

import lightning as L
import matplotlib.pyplot as plt
import torch
import torch.nn.functional as F
import torchvision
from torch import nn
from torch.utils.data import DataLoader, Subset
from torchmetrics.classification import MulticlassAccuracy
from torchvision import transforms


def quiet_lightning():
    """Silence Lightning's info logs and dataloader warnings for a tidy notebook."""
    import logging
    import warnings

    logging.getLogger("lightning.pytorch").setLevel(logging.ERROR)
    logging.getLogger("lightning.pytorch.utilities.rank_zero").setLevel(logging.ERROR)
    warnings.filterwarnings("ignore", ".*does not have many workers.*")
    warnings.filterwarnings("ignore", ".*litlogger.*")


DATA_DIR = Path(__file__).parent / "data"

# Measured during implementation on CPU, SGD(lr=0.01, momentum=0.9), 5 epochs,
# 6000 training images.  See plan.md "Author notes".
CHANCE_LOSS = math.log(10)          # 2.3026 -- a model guessing uniformly
N_TRAIN, N_TEST = 6000, 2000
EPOCHS, LR, BATCH = 5, 0.01, 128
MEAN, STD = 0.1307, 0.3081


# --------------------------------------------------------------------------
# data
# --------------------------------------------------------------------------
class MNISTDataModule(L.LightningDataModule):
    """A fixed stratified subsample of MNIST, small enough for four CPU runs.

    The subsample indices are drawn with a fixed generator, so every student
    trains on exactly the same images as the marker.
    """

    def __init__(self, n_train=N_TRAIN, n_test=N_TEST, batch_size=BATCH):
        super().__init__()
        self.save_hyperparameters()
        self.tf = transforms.Compose(
            [transforms.ToTensor(), transforms.Normalize((MEAN,), (STD,))]
        )

    def prepare_data(self):
        torchvision.datasets.MNIST(DATA_DIR, train=True, download=True)
        torchvision.datasets.MNIST(DATA_DIR, train=False, download=True)

    def setup(self, stage=None):
        full_train = torchvision.datasets.MNIST(
            DATA_DIR, train=True, download=False, transform=self.tf
        )
        full_test = torchvision.datasets.MNIST(
            DATA_DIR, train=False, download=False, transform=self.tf
        )
        g = torch.Generator().manual_seed(0)
        idx = torch.randperm(len(full_train), generator=g)[: self.hparams.n_train]
        self.train_set = Subset(full_train, idx.tolist())
        g = torch.Generator().manual_seed(1)
        idx = torch.randperm(len(full_test), generator=g)[: self.hparams.n_test]
        self.test_set = Subset(full_test, idx.tolist())

    def train_dataloader(self):
        return DataLoader(
            self.train_set, batch_size=self.hparams.batch_size, shuffle=True
        )

    def val_dataloader(self):
        return DataLoader(self.train_set, batch_size=512)

    def test_dataloader(self):
        return DataLoader(self.test_set, batch_size=512)


# --------------------------------------------------------------------------
# reference code used by the checks
# --------------------------------------------------------------------------
def reference_conv_block(c_in, c_out):
    """Exercise 1a's answer, used only to check the student's version."""
    return nn.Sequential(
        nn.Conv2d(c_in, c_out, kernel_size=3, padding=1),
        nn.ReLU(),
        nn.MaxPool2d(2),
    )


STAGES = [(1, 16), (16, 32), (32, 64)]  # every network uses these widths
HEAD_IN = 64 * 3 * 3                    # 28 -> 14 -> 7 -> 3


def n_conv(model):
    """Number of Conv2d modules anywhere in the model."""
    return sum(1 for m in model.modules() if isinstance(m, nn.Conv2d))


def n_params(model):
    return sum(p.numel() for p in model.parameters())


# --------------------------------------------------------------------------
# models
# --------------------------------------------------------------------------
class LitClassifier(L.LightningModule):
    """Wraps any backbone into a Lightning module.

    Exercise 1c asks only for ``training_step``; everything else is provided,
    and the same subclass is then reused for all four networks.
    """

    def __init__(self, net, lr=LR):
        super().__init__()
        self.net = net
        self.lr = lr
        self.train_acc = MulticlassAccuracy(num_classes=10)
        self.test_acc = MulticlassAccuracy(num_classes=10)

    def forward(self, x):
        return self.net(x)

    def training_step(self, batch, batch_idx):
        raise NotImplementedError("Exercise 1c: implement training_step")

    # -- provided --
    def configure_optimizers(self):
        return torch.optim.SGD(self.parameters(), lr=self.lr, momentum=0.9)

    def validation_step(self, batch, batch_idx):
        x, y = batch
        logits = self(x)
        self.log("train_loss", F.cross_entropy(logits, y), on_epoch=True)
        self.log("train_acc", self.train_acc(logits, y), on_epoch=True, prog_bar=True)

    def test_step(self, batch, batch_idx):
        x, y = batch
        logits = self(x)
        self.log("test_acc", self.test_acc(logits, y), prog_bar=True)


def make_trainer(max_epochs=EPOCHS, quiet=True, callbacks=None):
    """A CPU trainer that keeps every student's numbers identical to the marker's."""
    return L.Trainer(
        max_epochs=max_epochs,
        callbacks=callbacks or [],
        accelerator="cpu",
        logger=False,
        enable_checkpointing=False,
        enable_model_summary=False,
        enable_progress_bar=not quiet,
        log_every_n_steps=10,
        num_sanity_val_steps=0,
    )


class History(L.Callback):
    """Collects the per-epoch training loss and accuracy so they can be plotted."""

    def __init__(self):
        self.losses, self.accs = [], []

    def on_validation_epoch_end(self, trainer, pl_module):
        m = trainer.callback_metrics
        loss = m.get("train_loss_epoch", m.get("train_loss"))
        acc = m.get("train_acc_epoch", m.get("train_acc"))
        if loss is not None:
            self.losses.append(float(loss))
        if acc is not None:
            self.accs.append(float(acc))


def fit(model, dm, max_epochs=EPOCHS, seed=0):
    """Train a LitClassifier and return (history, test_accuracy).

    Re-seeds first, so every run starts from the same initialisation.
    """
    L.seed_everything(seed, workers=True)
    hist = History()
    trainer = make_trainer(max_epochs, callbacks=[hist])
    trainer.fit(model, datamodule=dm)
    test_acc = float(trainer.test(model, datamodule=dm, verbose=False)[0]["test_acc"])
    return hist, test_acc


def first_conv_grad_norm(net, batch):
    """Gradient norm at the first convolution after one backward pass.

    Provided so Exercise 3c measures gradient flow without boilerplate.
    """
    net.zero_grad()
    x, y = batch
    F.cross_entropy(net(x), y).backward()
    first = next(m for m in net.modules() if isinstance(m, nn.Conv2d))
    return float(first.weight.grad.norm())


# --------------------------------------------------------------------------
# plotting
# --------------------------------------------------------------------------
def show_digits(dm, n=8):
    dm.setup()
    x, y = next(iter(DataLoader(dm.train_set, batch_size=n, shuffle=False)))
    fig, axes = plt.subplots(1, n, figsize=(1.3 * n, 1.8))
    for ax, img, label in zip(axes, x, y):
        ax.imshow(img.squeeze() * STD + MEAN, cmap="gray")
        ax.set_title(int(label), fontsize=10)
        ax.axis("off")
    fig.suptitle(f"MNIST subsample: {len(dm.train_set)} train, {len(dm.test_set)} test")
    plt.tight_layout()
    plt.show()


def plot_curves(histories, title="training loss", chance=True):
    """histories: dict of name -> History (or list of losses)."""
    fig, ax = plt.subplots(figsize=(6, 3.6))
    for name, h in histories.items():
        losses = h.losses if hasattr(h, "losses") else h
        ax.plot(range(1, len(losses) + 1), losses, marker="o", label=name)
    if chance:
        ax.axhline(
            CHANCE_LOSS, ls="--", color="0.5",
            label=f"chance, ln 10 = {CHANCE_LOSS:.3f}",
        )
    ax.set_xlabel("epoch")
    ax.set_ylabel("training loss")
    ax.set_title(title)
    ax.legend(fontsize=8)
    plt.tight_layout()
    plt.show()


def summary_table(rows):
    """rows: list of (name, train_loss, train_acc, test_acc)."""
    head = f"{'network':<24}{'train loss':>12}{'train acc':>11}{'test acc':>10}"
    print(head)
    print("-" * len(head))
    for name, tl, ta, tea in rows:
        print(f"{name:<24}{tl:>12.4f}{ta:>11.3f}{tea:>10.3f}")


# --------------------------------------------------------------------------
# verification
# --------------------------------------------------------------------------
class CheckFailed(AssertionError):
    pass


def check(condition, message):
    if not condition:
        raise CheckFailed(message)


def check_conv_block(fn):
    """Exercise 1a."""
    try:
        got = fn(1, 16)
    except NotImplementedError:
        raise CheckFailed("conv_block is not implemented yet.")
    x = torch.randn(8, 1, 28, 28)
    with torch.no_grad():
        out = got(x)
    check(
        out.shape == (8, 16, 14, 14),
        f"conv_block(1, 16) on a (8,1,28,28) input gave {tuple(out.shape)}, "
        "expected (8, 16, 14, 14) -- is the MaxPool2d(2) there, and padding=1 on the conv?",
    )
    for c_in, c_out in [(1, 16), (16, 32), (32, 64)]:
        want = 9 * c_in * c_out + c_out
        have = n_params(fn(c_in, c_out))
        check(
            have == want,
            f"conv_block({c_in}, {c_out}) has {have} parameters, expected {want} "
            f"= 9*{c_in}*{c_out} + {c_out} -- a 3x3 kernel per input/output channel pair, "
            "plus one bias per output channel.",
        )
    check(
        n_conv(fn(1, 16)) == 1,
        f"conv_block should hold exactly one Conv2d, found {n_conv(fn(1, 16))}.",
    )
    print("[ok] 1a: conv_block halves the resolution and has 9*c_in*c_out + c_out parameters.")


def check_shallow(model):
    """Exercise 1b."""
    check(isinstance(model, nn.Module), f"expected an nn.Module, got {type(model).__name__}.")
    check(
        n_conv(model) == 3,
        f"ShallowCNN has {n_conv(model)} Conv2d layers, expected 3 -- one per stage.",
    )
    x = torch.randn(4, 1, 28, 28)
    with torch.no_grad():
        out = model(x)
    check(
        out.shape == (4, 10),
        f"forward gave {tuple(out.shape)}, expected (4, 10) -- ten classes, one row per image.",
    )
    print("[ok] 1b: ShallowCNN is 3 convolutions, 28 -> 14 -> 7 -> 3, and outputs 10 logits.")


def check_shallow_training(history, test_acc):
    """Exercise 1c."""
    check(
        len(history.losses) >= 2,
        f"only {len(history.losses)} epoch losses were recorded -- did the trainer run?",
    )
    check(
        history.losses[-1] < history.losses[0],
        f"training loss went from {history.losses[0]:.4f} to {history.losses[-1]:.4f} "
        "-- it should fall. Is training_step returning the cross-entropy loss?",
    )
    check(
        test_acc > 0.90,
        f"test accuracy {test_acc:.3f} is below 0.90; a 3-layer convnet on this subsample "
        "reaches about 0.95-0.97.",
    )
    print(
        f"[ok] 1c: training loss fell to {history.losses[-1]:.4f} and test accuracy is "
        f"{test_acc:.3f}."
    )


def check_plain_deep(model):
    """Exercise 2a."""
    check(
        n_conv(model) == 9,
        f"PlainDeepCNN has {n_conv(model)} Conv2d layers, expected 9 "
        "-- three per stage, three stages.",
    )
    x = torch.randn(4, 1, 28, 28)
    with torch.no_grad():
        out = model(x)
    check(
        out.shape == (4, 10),
        f"forward gave {tuple(out.shape)}, expected (4, 10). If the flatten size is wrong, "
        f"remember the head takes {HEAD_IN} features: 64 channels at 3x3.",
    )
    n_pool = sum(1 for m in model.modules() if isinstance(m, nn.MaxPool2d))
    check(
        n_pool == 3,
        f"found {n_pool} MaxPool2d layers, expected 3 -- one at the end of each stage, "
        "not one after every convolution.",
    )
    print("[ok] 2a: PlainDeepCNN is 9 convolutions with the same widths and pooling as the shallow net.")


def check_depth_comparison(shallow_hist, deep_hist):
    """Exercise 2b."""
    check(
        len(shallow_hist.losses) == len(deep_hist.losses),
        "the two runs have different numbers of epochs; train them with identical settings "
        "or the comparison means nothing.",
    )
    check(len(deep_hist.losses) >= 2, "the deep network recorded fewer than two epochs.")
    print(
        f"[ok] 2b: both networks trained for {len(deep_hist.losses)} epochs under identical "
        "settings."
    )


def check_degradation(shallow_train_loss, deep_train_loss, deep_train_acc):
    """Exercise 2c -- the reading, not just the numbers."""
    check(
        shallow_train_loss < 0.5,
        f"the shallow network's training loss is {shallow_train_loss:.4f}; expected below "
        "0.5. Check Exercise 1 before reading anything into the comparison.",
    )
    check(
        deep_train_loss > 2.0,
        f"the deep network's training loss is {deep_train_loss:.4f}; expected above 2.0. "
        "If it trained successfully, check that no batch normalization crept in and that "
        "the optimiser is SGD -- Adam masks this effect entirely.",
    )
    check(
        deep_train_acc < 0.2,
        f"the deep network's training accuracy is {deep_train_acc:.3f}; expected below 0.2.",
    )
    print(
        f"[ok] 2c: shallow training loss {shallow_train_loss:.4f}, deep {deep_train_loss:.4f} "
        f"-- within {abs(deep_train_loss - CHANCE_LOSS):.4f} of the chance line "
        f"{CHANCE_LOSS:.4f}."
    )
    print(
        "     The deeper network is worse on the data it was FITTED to, so this is not "
        "overfitting:\n"
        "     an overfitting model fits its training set better, not worse. It is a failure "
        "to optimise."
    )


def check_residual_block(block_cls):
    """Exercise 3a -- the identity test is what proves the skip is wired up."""
    try:
        block = block_cls(16)
    except NotImplementedError:
        raise CheckFailed("ResidualBlock is not implemented yet.")
    check(isinstance(block, nn.Module), "ResidualBlock should subclass nn.Module.")
    check(
        n_conv(block) == 2,
        f"the block holds {n_conv(block)} Conv2d layers, expected 2.",
    )
    z = torch.rand(4, 16, 14, 14)  # non-negative, so a trailing ReLU is the identity
    with torch.no_grad():
        out = block(z)
    check(
        out.shape == z.shape,
        f"the block changed the shape from {tuple(z.shape)} to {tuple(out.shape)}; a residual "
        "block must preserve it, or the addition cannot happen.",
    )
    # zero the second convolution: the block must now be the identity
    convs = [m for m in block.modules() if isinstance(m, nn.Conv2d)]
    with torch.no_grad():
        nn.init.zeros_(convs[-1].weight)
        if convs[-1].bias is not None:
            nn.init.zeros_(convs[-1].bias)
        out = block(z)
    check(
        torch.allclose(out, z, atol=1e-6),
        f"with the second convolution zeroed the block should return its input unchanged, "
        f"but the largest difference is {(out - z).abs().max():.4g}. That means the skip "
        "connection is missing -- the block must compute z + f(z), not just f(z).",
    )
    print("[ok] 3a: the block preserves shape, and reduces to the identity when f is zeroed.")


def check_residual_training(model, hist, test_acc, plain_train_loss):
    """Exercise 3b."""
    check(
        n_conv(model) == 9,
        f"ResidualDeepCNN has {n_conv(model)} convolutions, expected 9 -- the same as "
        "PlainDeepCNN, or the comparison is not controlled.",
    )
    check(
        hist.losses[-1] < 0.5,
        f"final training loss {hist.losses[-1]:.4f}; expected below 0.5. The residual "
        "version should train where the plain one could not.",
    )
    check(
        hist.losses[-1] < plain_train_loss,
        f"the residual network's training loss {hist.losses[-1]:.4f} is not below the plain "
        f"network's {plain_train_loss:.4f}.",
    )
    check(test_acc > 0.90, f"test accuracy {test_acc:.3f} is below 0.90.")
    print(
        f"[ok] 3b: same 9 convolutions, training loss {hist.losses[-1]:.4f} against the plain "
        f"network's {plain_train_loss:.4f}, test accuracy {test_acc:.3f}."
    )


def check_batchnorm_and_flow(rows, plain_norm, res_norm, bn_test_acc, no_bn_test_acc):
    """Exercise 3c."""
    check(
        len(rows) == 4,
        f"the summary has {len(rows)} rows, expected 4 -- shallow, plain deep, residual, "
        "residual + BN.",
    )
    check(
        res_norm > 10 * plain_norm,
        f"the residual network's first-conv gradient norm is {res_norm:.3e} against the "
        f"plain network's {plain_norm:.3e}, a factor of {res_norm / max(plain_norm, 1e-30):.1f}. "
        "Expected at least 10x. Are both measured at initialisation on the same batch?",
    )
    check(
        bn_test_acc > 0.95,
        f"test accuracy with batch norm is {bn_test_acc:.3f}; expected above 0.95.",
    )
    print(
        f"[ok] 3c: first-conv gradient norm {plain_norm:.3e} (plain) -> {res_norm:.3e} "
        f"(residual), a factor of {res_norm / max(plain_norm, 1e-30):.0f}."
    )
    print(
        f"     Batch norm lifted test accuracy from {no_bn_test_acc:.3f} to {bn_test_acc:.3f}."
    )
    print(
        "     Rows 2 and 3 are the controlled comparison: same depth, same widths, same\n"
        "     convolution count. The only difference is the skip connection."
    )
