"""Support code for CSCI 4052U Lab 1.

Students do not edit this file.  It provides:

* data           -- ``SineDataModule``, ``MNIST1DDataModule``
* reference code -- ``reference_shallow_net`` used to check Exercise 1
* models         -- ``LitRegressor``, ``LitClassifier`` (methods left for the student)
* plotting       -- ``plot_datasets``, ``plot_shallow_network``, ``plot_fit``,
                    ``plot_capacity_sweep``
* verification   -- the ``check_*`` functions called after each student cell
"""

from __future__ import annotations

import math
import pickle
import urllib.request
from pathlib import Path

import lightning as L
import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn.functional as F
from torch import nn
from torch.utils.data import DataLoader, TensorDataset
from torchmetrics.classification import MulticlassAccuracy

def quiet_lightning():
    """Silence Lightning's info logs and dataloader warnings for a tidy notebook."""
    import logging
    import warnings

    logging.getLogger("lightning.pytorch").setLevel(logging.ERROR)
    logging.getLogger("lightning.pytorch.utilities.rank_zero").setLevel(logging.ERROR)
    warnings.filterwarnings("ignore", ".*does not have many workers.*")
    warnings.filterwarnings("ignore", ".*litlogger.*")


DATA_DIR = Path(__file__).parent / "data"
MNIST1D_URL = "https://github.com/greydanus/mnist1d/raw/master/mnist1d_data.pkl"

# The worked example from the `preliminaries_to_machine_learning` notes.
EXAMPLE_THETA = torch.tensor([[-0.2, 0.4], [-0.9, 0.9], [1.1, -0.7]])
EXAMPLE_PHI = torch.tensor([-0.23, -1.3, 1.3, 0.66])


# --------------------------------------------------------------------------
# data
# --------------------------------------------------------------------------
def make_sine_data(n, noise=0.1, seed=0):
    """``n`` points of y = sin(2 pi x) + noise, with x drawn uniformly on [0, 1]."""
    g = torch.Generator().manual_seed(seed)
    x = torch.rand(n, generator=g)
    y = torch.sin(2 * math.pi * x) + noise * torch.randn(n, generator=g)
    return x.unsqueeze(1), y.unsqueeze(1)


class SineDataModule(L.LightningDataModule):
    """The 1D regression set.  ``n_train`` points to fit, ``n_test`` held out."""

    def __init__(self, n_train=60, n_test=200, batch_size=16, noise=0.1):
        super().__init__()
        self.save_hyperparameters()
        self.noise = noise
        x, y = make_sine_data(n_train + n_test, noise=noise, seed=0)
        self.x_train, self.y_train = x[:n_train], y[:n_train]
        self.x_test, self.y_test = x[n_train:], y[n_train:]

    def train_dataloader(self):
        ds = TensorDataset(self.x_train, self.y_train)
        return DataLoader(ds, batch_size=self.hparams.batch_size, shuffle=True)

    def val_dataloader(self):
        # the training points again, scored in one batch -- this is the train error
        ds = TensorDataset(self.x_train, self.y_train)
        return DataLoader(ds, batch_size=len(ds))

    def test_dataloader(self):
        ds = TensorDataset(self.x_test, self.y_test)
        return DataLoader(ds, batch_size=len(ds))


def download_mnist1d(data_dir=DATA_DIR):
    """Fetch the MNIST-1D pickle once and cache it, so re-runs work offline."""
    data_dir = Path(data_dir)
    data_dir.mkdir(exist_ok=True)
    path = data_dir / "mnist1d_data.pkl"
    if not path.exists():
        print(f"downloading MNIST-1D to {path} ...")
        urllib.request.urlretrieve(MNIST1D_URL, path)
    with open(path, "rb") as fh:
        return pickle.load(fh)


class MNIST1DDataModule(L.LightningDataModule):
    """MNIST-1D: 4000 training and 1000 test examples, 40 inputs, 10 classes."""

    def __init__(self, batch_size=100, label_noise=0.0):
        super().__init__()
        self.save_hyperparameters()
        d = download_mnist1d()
        self.x_train = torch.tensor(d["x"], dtype=torch.float32)
        self.y_train = torch.tensor(d["y"], dtype=torch.long)
        self.x_test = torch.tensor(d["x_test"], dtype=torch.float32)
        self.y_test = torch.tensor(d["y_test"], dtype=torch.long)
        if label_noise > 0:  # used only by the optional double-descent experiment
            g = torch.Generator().manual_seed(0)
            n = int(label_noise * len(self.y_train))
            idx = torch.randperm(len(self.y_train), generator=g)[:n]
            self.y_train[idx] = torch.randint(0, 10, (n,), generator=g)

    def train_dataloader(self):
        ds = TensorDataset(self.x_train, self.y_train)
        return DataLoader(ds, batch_size=self.hparams.batch_size, shuffle=True)

    def val_dataloader(self):
        ds = TensorDataset(self.x_train, self.y_train)
        return DataLoader(ds, batch_size=1000)

    def test_dataloader(self):
        ds = TensorDataset(self.x_test, self.y_test)
        return DataLoader(ds, batch_size=1000)


# --------------------------------------------------------------------------
# reference network for Exercise 1
# --------------------------------------------------------------------------
def reference_shallow_net(theta, phi):
    """The same shallow network as Exercise 1, built as an ``nn.Sequential``.

    ``theta`` is (D, 2) holding the intercept and slope of each hidden unit;
    ``phi`` is (D + 1,) holding the output offset followed by the output weights.
    """
    d = theta.shape[0]
    net = nn.Sequential(nn.Linear(1, d), nn.ReLU(), nn.Linear(d, 1))
    with torch.no_grad():
        net[0].bias.copy_(theta[:, 0])
        net[0].weight.copy_(theta[:, 1].unsqueeze(1))
        net[2].bias.copy_(phi[:1])
        net[2].weight.copy_(phi[1:].unsqueeze(0))
    return net


# --------------------------------------------------------------------------
# models
# --------------------------------------------------------------------------
class LitRegressor(L.LightningModule):
    """A two-hidden-layer regressor for the 1D sine data.

    Exercise 2b asks for ``__init__`` (the backbone), ``training_step`` and
    ``configure_optimizers``; subclass this in the notebook and override them.
    """

    def __init__(self, width=20, lr=0.01):
        super().__init__()
        self.save_hyperparameters()
        self.net = None  # YOUR CODE HERE (Exercise 2b)

    def forward(self, x):
        return self.net(x)

    def training_step(self, batch, batch_idx):
        raise NotImplementedError("Exercise 2b: implement training_step")

    def configure_optimizers(self):
        raise NotImplementedError("Exercise 2b: implement configure_optimizers")

    # -- provided: both hooks score mean squared error --
    def validation_step(self, batch, batch_idx):
        x, y = batch
        self.log("train_mse", F.mse_loss(self(x), y), prog_bar=True)

    def test_step(self, batch, batch_idx):
        x, y = batch
        self.log("test_mse", F.mse_loss(self(x), y))


class LitClassifier(L.LightningModule):
    """A two-hidden-layer classifier for MNIST-1D.

    Exercise 2c asks only for ``training_step``; everything else is provided.
    """

    def __init__(self, width=100, lr=0.1, n_inputs=40, n_classes=10):
        super().__init__()
        self.save_hyperparameters()
        self.net = nn.Sequential(
            nn.Linear(n_inputs, width),
            nn.ReLU(),
            nn.Linear(width, width),
            nn.ReLU(),
            nn.Linear(width, n_classes),
        )
        self.train_acc = MulticlassAccuracy(num_classes=n_classes)
        self.test_acc = MulticlassAccuracy(num_classes=n_classes)

    def forward(self, x):
        return self.net(x)

    def training_step(self, batch, batch_idx):
        raise NotImplementedError("Exercise 2c: implement training_step")

    # -- provided --
    def configure_optimizers(self):
        return torch.optim.SGD(self.parameters(), lr=self.hparams.lr, momentum=0.9)

    def validation_step(self, batch, batch_idx):
        x, y = batch
        logits = self(x)
        self.log("train_loss", F.cross_entropy(logits, y))
        self.log("train_acc", self.train_acc(logits, y), prog_bar=True)

    def test_step(self, batch, batch_idx):
        x, y = batch
        logits = self(x)
        self.log("test_loss", F.cross_entropy(logits, y))
        self.log("test_acc", self.test_acc(logits, y), prog_bar=True)


def make_trainer(max_epochs, quiet=False):
    """A CPU trainer that records metrics in memory and keeps the output tidy."""
    return L.Trainer(
        max_epochs=max_epochs,
        accelerator="cpu",
        logger=False,
        enable_checkpointing=False,
        enable_model_summary=False,
        enable_progress_bar=not quiet,
        log_every_n_steps=1,
        num_sanity_val_steps=0,
    )


class LossHistory(L.Callback):
    """Collects the per-epoch training loss so it can be plotted."""

    def __init__(self):
        self.losses = []

    def on_train_epoch_end(self, trainer, pl_module):
        value = trainer.callback_metrics.get("train_loss_epoch")
        if value is None:
            value = trainer.callback_metrics.get("train_loss")
        if value is not None:
            self.losses.append(float(value))


# --------------------------------------------------------------------------
# plotting
# --------------------------------------------------------------------------
def plot_datasets(sine, mnist1d):
    fig, ax = plt.subplots(1, 2, figsize=(10, 3.2))
    ax[0].scatter(sine.x_train, sine.y_train, s=18, label="train")
    ax[0].scatter(sine.x_test, sine.y_test, s=6, alpha=0.35, label="test")
    ax[0].set(xlabel="$x$", ylabel="$y$", title="1D sine regression")
    ax[0].legend(fontsize=8)
    for k in range(3):
        idx = (mnist1d.y_train == k).nonzero()[0].item()
        ax[1].plot(mnist1d.x_train[idx], label=f"digit {k}")
    ax[1].set(xlabel="position", ylabel="value", title="MNIST-1D (3 examples)")
    ax[1].legend(fontsize=8)
    fig.tight_layout()
    plt.show()


def plot_fit(model, dm, title="fitted function"):
    grid = torch.linspace(0, 1, 400).unsqueeze(1)
    with torch.no_grad():
        pred = model(grid)
    fig, ax = plt.subplots(figsize=(5, 3.2))
    ax.scatter(dm.x_train, dm.y_train, s=18, color="0.4", label="train data")
    ax.plot(grid, pred, color="#2c5f70", lw=2, label="model")
    ax.set(xlabel="$x$", ylabel="$y$", title=title)
    ax.legend(fontsize=8)
    fig.tight_layout()
    plt.show()


def plot_capacity_sweep(widths, train_errors, test_errors, noise_floor=None):
    fig, ax = plt.subplots(figsize=(5.2, 3.4))
    ax.plot(widths, train_errors, "o-", label="train MSE")
    ax.plot(widths, test_errors, "s-", label="test MSE")
    if noise_floor is not None:
        ax.axhline(noise_floor, color="0.5", ls=":",
                   label=f"noise floor $\\sigma^2$ = {noise_floor:.3f}")
    ax.set_xscale("log", base=2)
    ax.set(xlabel="hidden width (capacity)", ylabel="mean squared error",
           title="capacity against error")
    ax.legend(fontsize=8)
    fig.tight_layout()
    plt.show()


# --------------------------------------------------------------------------
# verification
# --------------------------------------------------------------------------
class CheckFailed(AssertionError):
    pass


def check(condition, message):
    if not condition:
        raise CheckFailed(message)


def check_shallow_forward(fn):
    """Exercise 1a."""
    x = torch.linspace(0, 2, 1000)
    try:
        got = fn(x, EXAMPLE_THETA, EXAMPLE_PHI)
    except NotImplementedError:
        raise CheckFailed("shallow_forward is not implemented yet.")
    check(isinstance(got, torch.Tensor), f"expected a tensor, got {type(got).__name__}.")
    check(
        got.shape == x.shape,
        f"your output has shape {tuple(got.shape)}, expected {tuple(x.shape)} -- "
        "did you forget to sum over the hidden units?",
    )
    with torch.no_grad():
        want = reference_shallow_net(EXAMPLE_THETA, EXAMPLE_PHI)(x.unsqueeze(1)).squeeze(1)
    check(
        torch.allclose(got, want, atol=1e-6),
        f"largest disagreement with the reference network is {(got - want).abs().max():.4g}; "
        "check the ReLU and the output offset phi[0].",
    )
    print("[ok] 1a: shallow_forward matches the reference network to 1e-6.")


def check_joints_and_slope(joints, slope):
    """Exercise 1b."""
    joints = torch.as_tensor(joints, dtype=torch.float32).sort().values
    want = torch.tensor([0.5, 1.0, 1.1 / 0.7])
    check(
        joints.shape == want.shape,
        f"expected 3 joints, got {joints.numel()}.",
    )
    check(
        torch.allclose(joints, want, atol=1e-3),
        f"joints {joints.tolist()} should be {[round(v, 3) for v in want.tolist()]} "
        "-- each is at x = -theta_d0 / theta_d1.",
    )
    want_slope = 0.4 * -1.3 + -0.7 * 0.66  # = -0.982, which the notes round to -0.98
    check(
        abs(float(slope) - want_slope) < 2e-3,
        f"slope {float(slope):.4f} should be {want_slope:.3f} "
        "= theta_11 * phi_1 + theta_31 * phi_3.",
    )
    print("[ok] 1b: joints at {0.5, 1.0, 1.571} and the shaded-region slope is -0.982.")


def check_gaussian_nll(fn):
    """Exercise 2a."""
    g = torch.Generator().manual_seed(1)
    pred = torch.randn(25, 1, generator=g)
    y = pred + 0.3 * torch.randn(25, 1, generator=g)
    for sigma in (0.5, 1.0, 2.0):
        try:
            got = float(fn(pred, y, sigma))
        except NotImplementedError:
            raise CheckFailed("gaussian_nll is not implemented yet.")
        sse = float(((y - pred) ** 2).sum())
        want = 0.5 * sse / sigma**2 + len(y) * math.log(math.sqrt(2 * math.pi) * sigma)
        check(
            abs(got - want) < 1e-4,
            f"at sigma={sigma} you returned {got:.4f}, expected {want:.4f}. "
            "The NLL is 0.5 * SSE / sigma^2 + I * log(sqrt(2 pi) sigma).",
        )
    # the two criteria must rank parameter sets identically
    good, bad = pred, pred + 2.0
    check(
        (fn(good, y, 1.0) < fn(bad, y, 1.0))
        == (((y - good) ** 2).sum() < ((y - bad) ** 2).sum()),
        "your NLL ranks a good and a bad fit differently from least squares; "
        "they must agree, because least squares IS the Gaussian NLL up to a constant.",
    )
    print("[ok] 2a: your NLL equals 0.5*SSE/sigma^2 + const, and ranks fits like least squares.")


def check_regressor(model, dm, trainer, losses):
    """Exercise 2b."""
    with torch.no_grad():
        mse = float(F.mse_loss(model(dm.x_train), dm.y_train))
    check(
        mse < 0.05,
        f"final training MSE is {mse:.4f}, which should be below 0.05. "
        "Check the learning rate, the number of epochs, and that the loss is MSE.",
    )
    check(len(losses) >= 20, "fewer than 20 epochs were recorded -- did the trainer run?")
    first, last = np.mean(losses[:10]), np.mean(losses[-10:])
    check(
        last < first,
        f"the loss did not decrease (first 10 epochs {first:.4f}, last 10 {last:.4f}).",
    )
    print(f"[ok] 2b: training MSE {mse:.4f} < 0.05, and the loss fell from {first:.3f} to {last:.3f}.")


def check_classifier(results):
    """Exercise 2c."""
    acc = float(results[0]["test_acc"])
    check(
        acc > 0.55,
        f"test accuracy is {acc:.3f}, which should exceed 0.55. "
        "Check that training_step returns the cross-entropy of the logits against y.",
    )
    print(f"[ok] 2c: MNIST-1D test accuracy {acc:.3f} > 0.55 (the notes report about 0.60).")


def check_fit_and_score(fn):
    """Exercise 3a."""
    try:
        out = fn(16)
    except NotImplementedError:
        raise CheckFailed("fit_and_score is not implemented yet.")
    check(
        isinstance(out, tuple) and len(out) == 2,
        f"expected a (train_mse, test_mse) tuple, got {out!r}.",
    )
    train, test = float(out[0]), float(out[1])
    check(
        0 <= train and 0 <= test,
        f"errors must be non-negative, got ({train:.4f}, {test:.4f}).",
    )
    check(
        train <= test + 1e-6,
        f"train MSE {train:.4f} exceeds test MSE {test:.4f}; "
        "check that you are scoring the training split with the training data.",
    )
    print(f"[ok] 3a: width 16 gives train MSE {train:.4f} and test MSE {test:.4f}.")


def check_sweep(widths, train_errors, test_errors, noise_floor=None):
    """Exercise 3b."""
    check(
        len(widths) == len(train_errors) == len(test_errors),
        "the three lists must have the same length.",
    )
    check(len(widths) >= 5, "sweep at least five widths.")
    i_small, i_large = int(np.argmin(widths)), int(np.argmax(widths))
    check(
        train_errors[i_small] > train_errors[i_large],
        f"the smallest model (width {widths[i_small]}) has train MSE "
        f"{train_errors[i_small]:.4f}, which should exceed the largest model's "
        f"{train_errors[i_large]:.4f} -- that gap is what underfitting looks like.",
    )
    best = widths[int(np.argmin(test_errors))]
    gap = test_errors[i_large] - train_errors[i_large]
    print(f"[ok] 3b: underfitting confirmed at width {widths[i_small]}.")
    print(f"      test error is lowest at width {best}.")
    print(f"      the gap at width {widths[i_large]} is {gap:.4f}.")
    if noise_floor is not None:
        print(f"      the noise floor is sigma^2 = {noise_floor:.4f}; "
              f"the best test error is {min(test_errors):.4f}.")
    print("      use these three numbers in your table.")


def check_decomposition(widths, train_errors, test_errors, noise_floor,
                        underfit_error, gap, best_width):
    """Exercise 3c."""
    import numpy as _np

    i_small, i_large = int(_np.argmin(widths)), int(_np.argmax(widths))
    want_underfit = train_errors[i_small]
    want_gap = test_errors[i_large] - train_errors[i_large]
    want_best = widths[int(_np.argmin(test_errors))]

    check(
        abs(float(underfit_error) - want_underfit) < 1e-6,
        f"underfit_error is {float(underfit_error):.4f}, expected {want_underfit:.4f} "
        f"-- the TRAIN error at the smallest width ({widths[i_small]}).",
    )
    check(
        abs(float(gap) - want_gap) < 1e-6,
        f"gap is {float(gap):.4f}, expected {want_gap:.4f} "
        f"-- test minus train error at the largest width ({widths[i_large]}).",
    )
    check(
        int(best_width) == want_best,
        f"best_width is {int(best_width)}, expected {want_best} "
        "-- the width at which TEST error is smallest.",
    )
    check(
        min(test_errors) > noise_floor,
        f"the best test error {min(test_errors):.4f} should sit above the noise floor "
        f"{noise_floor:.4f}; no model can beat the floor.",
    )
    print("[ok] 3c: bias, variance and noise read off correctly.")
    print(f"      bias   -> train error {want_underfit:.4f} at width {widths[i_small]}: "
          "too inflexible to fit the data at all.")
    print(f"      variance -> train/test gap {want_gap:.4f} at width {widths[i_large]}: "
          "the extra capacity fits the sample, not the function.")
    print(f"      noise  -> test error bottoms at {min(test_errors):.4f}, above the "
          f"floor sigma^2 = {noise_floor:.4f}, which no model can cross.")
    print(f"      test error is lowest at width {want_best}.")
